/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import com.google.gson.Gson;

import java.util.LinkedHashMap;
import java.util.Map;

import org.example.list.MyStringUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
        System.out.println(MyStringUtils.reverse(result));

        Gson gson = new Gson();
        Map<String, Integer> map = new LinkedHashMap<>();
        map.put("USD", 123);
        map.put("EUR", 321);
        String json = gson.toJson(map);
        System.out.println(json);
    }
}